name: envify
description: A better way to handle environment variables using `.env` file.
version: 2.0.2
homepage: https://github.com/frencojobs/envify

publish_to: "none"

environment:
  sdk: ">=2.17.1 <3.0.0"

dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.1

scripts: ../derry.yaml
